apiVersion: apps/v1
kind: Deployment
metadata:
  name: secure-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: secure
  template:
    metadata:
      labels:
        app: secure
    spec:
      containers:
        - name: myapp
          image: nginx:1.14
          securityContext:
            runAsNonRoot: true
            runAsUser: 1000
          ports:
            - containerPort: 80
