pipeline {
  agent any
  stages {
    stage('Policy Check - Conftest') {
      steps {
        sh 'conftest test --policy ../lab1-conftest/policies ../lab1-conftest/manifests/deployment-insecure.yaml'
      }
    }
    stage('Policy Check - Checkov') {
      steps {
        sh 'checkov -d ../lab2-checkov/terraform'
      }
    }
  }
  post {
    always { echo 'Policy checks completed' }
  }
}
